# Generated by Django 4.2 on 2023-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                help_text="Don't share your ticket number", max_length=8, unique=True
            ),
        ),
    ]
