# Generated by Django 4.2 on 2023-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_ticket_ticket_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripbus",
            name="available_seats",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
