# Generated by Django 4.2 on 2023-05-03 13:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.PositiveIntegerField(unique=True)),
                ("number_of_seats", models.PositiveSmallIntegerField()),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Buses",
            },
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=100)),
                ("cost", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Seat 1"),
                            (2, "Seat 2"),
                            (3, "Seat 3"),
                            (4, "Seat 4"),
                            (5, "Seat 5"),
                            (6, "Seat 6"),
                            (7, "Seat 7"),
                            (8, "Seat 8"),
                            (9, "Seat 9"),
                            (10, "Seat 10"),
                            (11, "Seat 11"),
                            (12, "Seat 12"),
                            (13, "Seat 13"),
                            (14, "Seat 14"),
                            (15, "Seat 15"),
                            (16, "Seat 16"),
                            (17, "Seat 17"),
                            (18, "Seat 18"),
                            (19, "Seat 19"),
                            (20, "Seat 20"),
                            (21, "Seat 21"),
                            (22, "Seat 22"),
                            (23, "Seat 23"),
                            (24, "Seat 24"),
                            (25, "Seat 25"),
                            (26, "Seat 26"),
                            (27, "Seat 27"),
                            (28, "Seat 28"),
                            (29, "Seat 29"),
                            (30, "Seat 30"),
                        ]
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.bus"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus",
            name="driver",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.driver",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.busroute",
            ),
        ),
    ]
